apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qyfu1v3kl-nodejs 
  janus-idp.io/tekton: qyfu1v3kl-nodejs
  backstage.io/kubernetes-id: qyfu1v3kl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qyfu1v3kl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  